using System;
using FluentAssertions;
using NUnit.Framework;
using Puzzles.Core;
using Puzzles.Core.Helpers;

namespace Puzzles.ProjectEuler.Problems_0001_0100
{
    /// <summary>
    /// The sequence of triangle numbers is generated by adding the natural numbers. 
    /// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
    /// The first ten terms would be:
    /// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    /// 
    /// Let us list the factors of the first seven triangle numbers:
    ///
    /// 1: 1
    /// 3: 1,3
    /// 6: 1,2,3,6
    /// 10: 1,2,5,10
    /// 15: 1,3,5,15
    /// 21: 1,3,7,21
    /// 28: 1,2,4,7,14,28
    /// We can see that 28 is the first triangle number to have over five divisors.
    ///
    /// What is the value of the first triangle number to have over five hundred divisors?
    /// </summary>
    [TestFixture]
    public class Problem_0012_HighlyDivisibleTriangularNumber
    {
        /// <summary>
        /// 28: Five divisors
        /// </summary>
        [Test]
        public void FindFirstTriangleNumberWithOverFiveDivisors()
        {
            var number = FindTriangleNumber(5);

            Console.WriteLine("Number: {0}", number);
        }

        /// <summary>
        /// 76576500
        /// </summary>
        [Test]
        public void FindFirstTriangleNumberWithOverFiveHundredDivisors()
        {
            var number = FindTriangleNumber(500);

            Console.WriteLine("Number: {0}", number);

            number.Should().Be(76576500);
        }

        private static long FindTriangleNumber(int minimumNumberOfFactors)
        {
            long sequence = 1;
            long number = 1;

            while (true)
            {
                var factors = FactorHelper.GetFactorsOf(number);
                if (factors.Count > minimumNumberOfFactors)
                    break;

                sequence++;
                number += sequence;
            }

            return number;
        }

    }
}
