using System;
using System.Collections.Generic;
using FluentAssertions;
using NUnit.Framework;

namespace Puzzles.ProjectEuler.Problems_0001_0100
{
    /// Consider all integer combinations of apowerb for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
    ///
    /// 2squared=4, 2cubed=8, 2power4=16, 2power5=32
    /// 3squared=9, 3cubed=27, 3power4=81, 3power5=243
    /// 4squared=16, 4cubed=64, 4power4=256, 4power5=1024
    /// 5squared=25, 5cubed=125, 5power4=625, 5power5=3125
    /// If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
    ///
    /// 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
    ///
    /// How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
    [TestFixture]
    public class Problem_0029_DistinctPowers
    {
        [Test]
        [TestCase(2, 5, 2, 5, 15)]
        public void ConfirmDistinctTerms(int minA, int maxA, int minB, int maxB, int expectedNumberTerms)
        {
            var getNumberTerms = GetTermCount(minA, maxA, minB, maxB);
            Assert.AreEqual(expectedNumberTerms, getNumberTerms);
        }

        [Test]
        public void FindNumberOfTermsForRangeToAHundred()
        {
            var getNumberTerms = GetTermCount(2, 100, 2, 100);

            Console.WriteLine(getNumberTerms);

            getNumberTerms.Should().Be(9183);
        }

        private static int GetTermCount(int minA, int maxA, int minB, int maxB)
        {
            var terms = new HashSet<double>();

            for (var a = minA; a <= maxA; ++a)
            {
                for (var b = minB; b <= maxB; ++b)
                {
                    var term = Math.Pow(a, b);
                    if (!terms.Contains(term))
                        terms.Add(term);
                }
            }

            return terms.Count;
        }

    }
}
