using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using NUnit.Framework;

namespace Puzzles.ProjectEuler.Problems_0001_0100
{
    /// <summary>
    /// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    ///
    /// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    /// Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    /// Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
    /// It can be verified that T285 = P165 = H143 = 40755.
    ///
    /// Find the next triangle number that is also pentagonal and hexagonal.
    /// </summary>
    [TestFixture]
    public class Problem_0045_TriangularPentagonalAndHexagonal
    {
        private readonly List<long> triangles = new List<long>();
        private readonly List<long> pentagons = new List<long>();
        private readonly List<long> hexagons = new List<long>();

        [TestFixtureSetUp]
        public void FixtureSetUp()
        {
            for (var n = 1; n < 100000; ++n)
            {
                double t = (n * (n + 1D)) / 2;
                double p = (n * ((3D * n) - 1D)) / 2;
                double h = (n * ((2D * n) - 1D));

                triangles.Add((long)t);
                pentagons.Add((long)p);
                hexagons.Add((long)h);

                if (t < 0 || (long)t < 0 || p < 0 || h < 0)
                {
                    Console.WriteLine("n {0} gives negative", n);
                    break;
                }
            }
        }

        [Test]
        public void ConfirmNoNegatives()
        {
            Assert.IsFalse(triangles.Any(t => t < 0), "no negative triangles");
            Assert.IsFalse(hexagons.Any(h => h < 0), "negative hexagons");
            Assert.IsFalse(pentagons.Any(p => p < 0), "negative pentagons");
        }

        [Test]
        public void ConfirmTriangles()
        {
            //1, 3, 6, 10, 15
            Assert.IsTrue(triangles.Contains(1));
            Assert.IsTrue(triangles.Contains(3));
            Assert.IsTrue(triangles.Contains(6));
            Assert.IsTrue(triangles.Contains(10));
            Assert.IsTrue(triangles.Contains(15));
        }

        [Test]
        public void ConfirmPentagons()
        {
            // 1, 5, 12, 22, 35
            Assert.IsTrue(pentagons.Contains(1));
            Assert.IsTrue(pentagons.Contains(5));
            Assert.IsTrue(pentagons.Contains(12));
            Assert.IsTrue(pentagons.Contains(22));
            Assert.IsTrue(pentagons.Contains(35));
        }

        [Test]
        public void ConfirmHexagons()
        {
            // 1, 6, 15, 28, 45
            Assert.IsTrue(hexagons.Contains(1));
            Assert.IsTrue(hexagons.Contains(6));
            Assert.IsTrue(hexagons.Contains(15));
            Assert.IsTrue(hexagons.Contains(28));
            Assert.IsTrue(hexagons.Contains(45));
        }

        [Test]
        public void ConfirmExample()
        {
            const int candidate = 40755;
            Assert.IsTrue(triangles.Contains(candidate), "Triangle");
            Assert.IsTrue(pentagons.Contains(candidate), "Pentagon");
            Assert.IsTrue(hexagons.Contains(candidate), "Hexagon");
        }

        /// <summary>
        /// 1533776805
        /// </summary>
        [Test, Explicit]
        public void FindNextTripleNumber()
        {
            foreach (var hexagon in hexagons.Where(h => h > 40755))
            {
                if (!pentagons.Contains(hexagon)) continue;
                if (!triangles.Contains(hexagon)) continue;

                Console.WriteLine("Number: {0}", hexagon);
                hexagon.Should().Be(1533776805);
                break;
            }
        }
    }
}
