using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

namespace Puzzles.ProjectEuler.Problems_0001_0100
{
    /// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
    ///
    /// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    ///
    /// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
    ///
    /// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal
    /// and D = |Pk − Pj| is minimised; what is the value of D?
    [TestFixture]
    public class Problem_0044_PentagonNumbers
    {
        private List<int> pentagonalNumbers;

        [TestFixtureSetUp]
        public void FixtureSetUp()
        {
            pentagonalNumbers = new List<int>();
            for (var n = 1; n < 3000; ++n)
            {
                var pentagonal = (n * ((3 * n) - 1)) / 2;
                pentagonalNumbers.Add((int)pentagonal);
            }
        }

        [Test]
        [TestCase(1, true)]
        [TestCase(5, true)]
        [TestCase(12, true)]
        [TestCase(22, true)]
        [TestCase(35, true)]
        [TestCase(51, true)]
        [TestCase(70, true)]
        [TestCase(92, true)]
        [TestCase(117, true)]
        [TestCase(145, true)]
        [TestCase(2, false)]
        public void ConfirmPentagonal(int candidate, bool expectedResult)
        {
            var isPentagonal = IsPentagonal(candidate);
            Assert.AreEqual(expectedResult, isPentagonal);
        }

        /// <summary>
        /// 5482660 (from 1560090 and 7042750)
        /// </summary>
        [Test, Explicit]
        public void BruteForceFindPentagonalPairsWithSumDifferencePentagonal()
        {
            var list = new List<PentagonalPair>();

            foreach (var a in pentagonalNumbers)
            {
                var aValue = a;
                foreach (var b in pentagonalNumbers.Where(n => n > aValue))
                {
                    if (a == b) continue;

                    var sum = a + b;
                    if (!pentagonalNumbers.Contains(sum)) continue;
                    var diff = b - a;
                    if (!pentagonalNumbers.Contains(diff)) continue;

                    var pair = new PentagonalPair(a, b);
                    list.Add(pair);
                }
            }

            foreach (var pentagonalPair in list.OrderByDescending(pair => Math.Abs(pair.difference)))
            {
                Console.WriteLine(pentagonalPair);
            }
        }

        private bool IsPentagonal(int candidate)
        {
            return pentagonalNumbers.Contains(candidate);
        }
    }

    public struct PentagonalPair
    {
        public int a { get; private set; }
        public int b { get; private set; }
        public int sum { get { return a + b; } }
        public int difference { get { return b - a; } }

        public PentagonalPair(int a, int b)
            : this()
        {
            this.a = a;
            this.b = b;
        }

        public override string ToString()
        {
            return string.Format("Diff: {0} from a {1} and b {2} (sum {3})", difference, a, b, sum);
        }
    }
}
