using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using NUnit.Framework;
using Puzzles.Core.Helpers;

namespace Puzzles.ProjectEuler.Problems_0001_0100
{
    /// <summary>
    /// Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers 
    /// and are generated by the following formulae:
    ///
    /// Triangle	 	P3,n => n(n+1)/2	 	1, 3, 6, 10, 15, ...
    /// Square	 	    P4,n => n^2	            1, 4, 9, 16, 25, ...
    /// Pentagonal	 	P5,n => n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    /// Hexagonal	 	P6,n => n(2n−1)	 	    1, 6, 15, 28, 45, ...
    /// Heptagonal	 	P7,n => n(5n−3)/2	 	1, 7, 18, 34, 55, ...
    /// Octagonal	 	P8,n => n(3n−2)	 	    1, 8, 21, 40, 65, ...
    /// The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
    ///
    /// The set is cyclic, in that the last two digits of each number is the first two digits of the next number 
    /// (including the last number with the first).
    /// Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), 
    /// is represented by a different number in the set.
    /// This is the only set of 4-digit numbers with this property.
    /// Find the sum of the only ordered set of six cyclic 4-digit numbers 
    /// for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, 
    /// is represented by a different number in the set.
    /// </summary>
    [TestFixture]
    public class Problem_0061_CyclicalFigurateNumbers
    {
        private const long lowerLimit = 999;
        private const long UpperLimit = 10000;

        /// <summary>
        ///   S0 = Number:8256 [Triangle] ,
        /// { S1 = Number:5625 [Square] , 
        ///   S2 = Number:2512 [Heptagon] , 
        ///   S3 = Number:1281 [Octagon] , 
        ///   S4 = Number:8128 [Hexagon] , 
        ///   S5 = Number:2882 [Pentagon]  }
        /// 
        /// 28684
        /// </summary>
        [Test, Explicit]
        public void FindSetOfSixCyclicNumbers()
        {
            var triangles = GetNumbers(ShapeHelper.GetTriangle);
            var squares = GetNumbers(SquareHelper.GetSquare);
            var pentagons = GetNumbers(ShapeHelper.GetPentagon);
            var hexagons = GetNumbers(ShapeHelper.GetHexagon);
            var heptagons = GetNumbers(ShapeHelper.GetHeptagon);
            var octagons = GetNumbers(ShapeHelper.GetOctagon);

            var list = triangles.Select(triangle => new CandidateNumber(Shape.Triangle, triangle)).ToList();
            list.AddRange(squares.Select(square => new CandidateNumber(Shape.Square, square)));
            list.AddRange(pentagons.Select(pentagon => new CandidateNumber(Shape.Pentagon, pentagon)));
            list.AddRange(hexagons.Select(hexagon => new CandidateNumber(Shape.Hexagon, hexagon)));
            list.AddRange(heptagons.Select(heptagon => new CandidateNumber(Shape.Heptagon, heptagon)));
            list.AddRange(octagons.Select(octagon => new CandidateNumber(Shape.Octagon, octagon)));

            var chain = from triangle in list
                        where triangle.Shape == Shape.Triangle
                        from shape in list
                        where shape.Shape != Shape.Triangle && shape.FirstTwoCharacters == triangle.LastTwoCharacters
                        from shape2 in list
                        where
                            shape2.Shape != Shape.Triangle && shape2.Shape != shape.Shape &&
                            shape2.FirstTwoCharacters == shape.LastTwoCharacters
                        from shape3 in list
                        where
                            shape3.Shape != Shape.Triangle && shape3.Shape != shape2.Shape && shape3.Shape != shape.Shape &&
                            shape3.FirstTwoCharacters == shape2.LastTwoCharacters
                        from shape4 in list
                        where
                            shape4.Shape != Shape.Triangle && shape4.Shape != shape3.Shape && shape4.Shape != shape2.Shape &&
                            shape4.Shape != shape.Shape &&
                            shape4.FirstTwoCharacters == shape3.LastTwoCharacters
                        from shape5 in list
                        where
                            shape5.Shape != Shape.Triangle && shape5.Shape != shape4.Shape && shape5.Shape != shape3.Shape &&
                            shape5.Shape != shape2.Shape && shape5.Shape != shape.Shape &&
                            shape5.FirstTwoCharacters == shape4.LastTwoCharacters &&
                            shape5.LastTwoCharacters == triangle.FirstTwoCharacters
                        //select new {S1 = shape, S2 = shape2, S3 = shape3, S4 = shape4};
                        select new { S0 = triangle, S1 = shape, S2 = shape2, S3 = shape3, S4 = shape4, S5 = shape5 };

            foreach (var ch in chain)
            {
                Console.WriteLine("{0}", ch);
            }
        }

        private IEnumerable<long> GetNumbers(Func<long, long> shapeFunction)
        {
            var list = new List<long>();

            var n = 10;
            var result = shapeFunction(n);

            while (result < UpperLimit)
            {
                if (result > lowerLimit)
                    list.Add(result);

                n++;
                result = shapeFunction(n);
            }

            return list;
        }
    }

    public enum Shape
    {
        Triangle,
        Square,
        Pentagon,
        Hexagon,
        Heptagon,
        Octagon
    }

    public class CandidateNumber
    {
        public Shape Shape { get; private set; }
        public long Number { get; private set; }
        public string FirstTwoCharacters { get; private set; }
        public string LastTwoCharacters { get; private set; }

        public CandidateNumber(Shape shape, long number)
        {
            Shape = shape;
            Number = number;

            if (Number < 1000 || Number > 9999)
                throw new ApplicationException("Number out of range!");

            var text = number.ToString(CultureInfo.InvariantCulture);
            FirstTwoCharacters = text.Substring(0, 2);
            LastTwoCharacters = text.Substring(2, 2);
        }

        public override string ToString()
        {
            return string.Format("Number:{0} [{1}] ", Number, Shape);
        }
    }
}
