using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using NUnit.Framework;

namespace Puzzles.ProjectEuler.Problems_0001_0100
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    /// By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    /// find the sum of the even-valued terms.
    /// </summary>
    [TestFixture]
    public class Problem_0002_EvenFibonacciNumbers
    {
        [Test]
        public void FindFibonacciUpTo90()
        {
            var fibonacciNumbers = FindFibonacciUpTo(90);

            Assert.AreEqual(10, fibonacciNumbers.Count, "Ten numbers found");

            Assert.AreEqual(1, fibonacciNumbers[0], "1");
            Assert.AreEqual(2, fibonacciNumbers[1], "2");
            Assert.AreEqual(3, fibonacciNumbers[2], "3");
            Assert.AreEqual(5, fibonacciNumbers[3], "5");
            Assert.AreEqual(8, fibonacciNumbers[4], "8");
            Assert.AreEqual(13, fibonacciNumbers[5], "13");
            Assert.AreEqual(21, fibonacciNumbers[6], "21");
            Assert.AreEqual(34, fibonacciNumbers[7], "34");
            Assert.AreEqual(55, fibonacciNumbers[8], "55");
            Assert.AreEqual(89, fibonacciNumbers[9], "89");
        }

        /// <summary>
        /// 4613732
        /// </summary>
        [Test, Explicit]
        public void FindSumOfEvenFibonacciUpToFourMillion()
        {
            var fibonacciNumbers = FindFibonacciUpTo(4000000);

            var sum = fibonacciNumbers.Where(fibonacciNumber => fibonacciNumber % 2 == 0).Sum();

            Console.WriteLine(sum);
            sum.Should().Be(4613732);
        }

        private IList<int> FindFibonacciUpTo(int limit)
        {
            var list = new List<int>();
            list.Add(1);
            list.Add(2);

            var previousNumber = 1;
            var lastNumber = 2;
            var nextNumber = previousNumber + lastNumber;

            while (nextNumber < limit)
            {
                list.Add(nextNumber);

                previousNumber = lastNumber;
                lastNumber = nextNumber;
                nextNumber = previousNumber + lastNumber;
            }
            return list;
        }
    }
}
